repos:
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "master"
    hooks:
      - id: flutter-import-sorter
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "master"
    hooks:
      - id: flutter-analyze
