name: flings
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter
  dominion: ^0.1.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  injectable: ^1.0.7
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  import_sorter: ^4.4.1
  injectable_generator: ^1.0.7
  mockito: ^4.1.3

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
  ignored_files:
    - .*\.g\.dart
    - .*\.config\.dart
    - .*\.freezed\.dart
    - .*\.gr\.dart
