name: flings
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  import_sorter: ^4.4.1

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
  ignored_files:
    - .*\.g\.dart
    - .*\.config\.dart
    - .*\.freezed\.dart
    - .*\.gr\.dart
