name: flings
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter
  dominion: ^0.1.0
  freezed_annotation: ^0.12.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  freezed: 0.12.5
  import_sorter: ^4.4.1

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
  ignored_files:
    - .*\.g\.dart
    - .*\.config\.dart
    - .*\.freezed\.dart
    - .*\.gr\.dart
